import { Inter } from "next/font/google";
import "./globals.css";
import "modern-normalize";
import AppBar from "./components/AppBar/AppBar";
import { Providers } from "./redux/providers";
import type { Metadata } from "next";

const font = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "TravelTrucks",
  icons: {
    icon: "/icons/title.svg",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.className}>
      <body>
        <Providers>
          <AppBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
